version: 2

project_name: writebook-cli

before:
  hooks:
    - sh -c "cd cli && go mod tidy"

builds:
  - id: writebook-cli
    binary: writebook-cli
    dir: ./cli
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "writebook-cli_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^style:"
      - "^test:"
